echo "Simple Printing"
echo "Hello World" 
echo "How are you doing"
echo "Fine?"
echo "Or Bad?"
echo "TELL ME!"
echo "TELL ME NOW!!!!!!!!!!!!"
echo "TELL MEEEEEEEEEEEEEEEEEEEEEEE NOW"
echo "GAY"
echo "Idk why I did this repo tbh"